#pragma once

// From glfw3.h
#define OKRA_MOUSE_BUTTON_1         0
#define OKRA_MOUSE_BUTTON_2         1
#define OKRA_MOUSE_BUTTON_3         2
#define OKRA_MOUSE_BUTTON_4         3
#define OKRA_MOUSE_BUTTON_5         4
#define OKRA_MOUSE_BUTTON_6         5
#define OKRA_MOUSE_BUTTON_7         6
#define OKRA_MOUSE_BUTTON_8         7
#define OKRA_MOUSE_BUTTON_LAST      OKRA_MOUSE_BUTTON_8
#define OKRA_MOUSE_BUTTON_LEFT      OKRA_MOUSE_BUTTON_1
#define OKRA_MOUSE_BUTTON_RIGHT     OKRA_MOUSE_BUTTON_2
#define OKRA_MOUSE_BUTTON_MIDDLE    OKRA_MOUSE_BUTTON_3